enum ipcNames {
  Test = 'main-process-message',
  update_available = 'update_available',
  update_not_available = 'update_not_available',
  update_progress = 'update_progress',
  update_error = 'update_error',
  update_downloaded = 'update_downloaded',
  quit_update = 'quit_update',
  maximize = 'maximize',
  quit = 'quit',
  minimize = "minimize",
  update_launch_status = "update_launch_status",
  auto_launch_enable = "auto_launch_enable",
  auto_launch_disable = "auto_launch_disable",
  auto_launch_status = "auto_launch_status",
  menu_cmd = "menu_cmd",
  add_child_process_name = "add_child_process_name"
}
export default ipcNames;